version: '3.7'

services:
  # cron:
  #   container_name: cron
  #   image: fulcrum/util
  #   network_mode: bridge
  #   tty: true
  #   volumes:
  #    - $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/cron/periodic:/etc/periodic:ro
  #   depends_on:
  #     - dnsmasq
  #   dns: $FULCRUM_HOST_IP
  #   entrypoint: /usr/sbin/crond
  #   command: -f

  # $FULCRUM_HOME_DC/fulcrum/var/lib/mysql is exported twice
  # for compatibility with debian and alpine mariadb
  mariadb:
    container_name: mariadb
    image: fulcrum/mariadb:latest
    network_mode: bridge
    volumes:
     - $FULCRUM_HOME_DC/fulcrum/etc/mysql:/etc/mysql:ro
     - $FULCRUM_HOME_DC/fulcrum/var/log/mariadb:/var/log
     - $FULCRUM_HOME_DC/fulcrum/var/lib/mysql:/var/lib/mysql
     - $FULCRUM_HOME_DC/fulcrum/var/lib/mysql:/data/mysql
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    depends_on:
      - dnsmasq
    dns: $FULCRUM_HOST_IP

  redis:
    container_name: redis
    image: fulcrum/redis:latest-alpine
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/redis/redis.conf:/etc/redis/redis.conf:ro
      - $FULCRUM_HOME_DC/fulcrum/var/log/redis:/var/log
    ports:
      - "6379:6379"
    depends_on:
      - dnsmasq
    dns: $FULCRUM_HOST_IP

  # memcached:
  #   container_name: memcached
  #   image: memcached:alpine
  #   network_mode: bridge
  #   ports:
  #     - "11211:11211"
  #   depends_on:
  #     - dnsmasq
  #   dns: $FULCRUM_HOST_IP

  php7.4:
    container_name: php7.4
    image: fulcrum/php7.4-drush8
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/php7.4:/usr/local/etc:ro
      - $FULCRUM_HOME_DC/fulcrum/var/log/php7.4:/usr/local/var/log
      - $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum.php:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum/fulcrum.php:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/private_files:/private
      - $FULCRUM_HOME_DC/fulcrum/sites:/var/www/html
    ports:
      - "9074:9074"
    depends_on:
      - dnsmasq
    dns: $FULCRUM_HOST_IP
    cap_add:
      - SYS_PTRACE

  nginx:
    container_name: nginx
    image: fulcrum/nginx:1.19
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/nginx:/etc/nginx
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/nginx/resolver.conf:/etc/nginx/conf.d/resolver.conf:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/nginx/fulcrum/fulcrum_proxypass.conf:/etc/nginx/fulcrum/fulcrum_proxypass.conf
      - $FULCRUM_HOME_DC/fulcrum/var/log/nginx:/var/log
      - $FULCRUM_HOME_DC/fulcrum/sites:/var/www/html:ro
    ports:
      - "8080:80"
    depends_on:
      - dnsmasq
    dns: $FULCRUM_HOST_IP

  varnish:
    container_name: varnish
    image: fulcrum/varnish:6.4
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish:/etc/varnish
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/backends-webs-decoupled.vcl:/etc/varnish/backends-webs.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/audience-public.vcl:/etc/varnish/include/audience.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/x-forward-for-localdev.vcl:/etc/varnish/include/x-forward-for.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/beresp-ttl-dev.vcl:/etc/varnish/include/beresp-ttl.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/cache-tag-debug.vcl:/etc/varnish/include/cache-tag-remove.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/log/varnish:/var/log
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_backend_response_tail.vcl:/etc/varnish/include/vcl_backend_response_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_deliver_tail.vcl:/etc/varnish/include/vcl_deliver_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_hash_tail.vcl:/etc/varnish/include/vcl_hash_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_hit_tail.vcl:/etc/varnish/include/vcl_hit_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_recv_tail.vcl:/etc/varnish/include/vcl_recv_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_miss_tail.vcl:/etc/varnish/include/vcl_miss_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_pass_tail.vcl:/etc/varnish/include/vcl_pass_tail.vcl:ro
    command: -F -P /var/run/varnish.pid -a :6081,PROXY -f /etc/varnish/default.vcl -S /etc/varnish/secret -T 0.0.0.0:6082 -t 120 -s malloc,128M -p workspace_backend=131072 -p http_resp_hdr_len=65536 -p http_resp_size=98304
    ports:
      - "6081:6081"
      - "6082:6082"
    depends_on:
      - dnsmasq
    dns: $FULCRUM_HOST_IP

  # 4433 is for testing, bypass varnish on TLS
  haproxy:
    container_name: haproxy
    image: fulcrum/haproxy:1.8
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/haproxy:/etc/haproxy
      - $FULCRUM_HOME_DC/fulcrum/etc/certs.d:/etc/certs.d:ro
      - $FULCRUM_HOME_DC/fulcrum/var/log/haproxy:/var/log
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/haproxy/local-dev.cfg:/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "443:443"
      - "4080:4080"
      - "4433:4433"
      - "5080:5080"
      - "1936:1936"
    depends_on:
      - dnsmasq
    dns: $FULCRUM_HOST_IP

  # solr7:
  #   container_name: solr7
  #   image: solr:7.7-alpine
  #   network_mode: bridge
  #   ports:
  #     - "8987:8983"
  #   volumes:
  #     - $FULCRUM_HOME_DC/fulcrum/var/log/solr7:/opt/solr/server/logs
  #     - $FULCRUM_HOME_DC/fulcrum/var/lib/solr7:/opt/solr/server/solr
  #     - $FULCRUM_HOME_DC/fulcrum/etc/solr7-copy-configs:/opt/solr-copy-configs
  #   depends_on:
  #     - dnsmasq
  #   dns: $FULCRUM_HOST_IP

  # elasticsearch7:
  #   container_name: elasticsearch7
  #   image: fulcrum/elasticsearch7.4
  #   network_mode: bridge
  #   ports:
  #     - "9207:9200"
  #     - "9307:9300"
  #   volumes:
  #      - $FULCRUM_HOME_DC/fulcrum/var/lib/elasticsearch7:/usr/share/elasticsearch/data
  #   depends_on:
  #     - dnsmasq
  #   dns: $FULCRUM_HOST_IP
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.type=single-node"

  dnsmasq:
    container_name: dnsmasq
    image: fulcrum/dnsmasq
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/dnsmasq:/etc/dnsmasq
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/dnsmasq/ifdev.conf:/etc/dnsmasq/ifdev.conf:ro
    cap_add:
      - NET_ADMIN
